set number
set tabstop=2
set expandtab
set shiftwidth=2
set nobackup
set noswapfile
set cursorline
set cursorcolumn
set hlsearch
set nowrap
set autoread
colorscheme molokai
set background=dark
syntax on

" dein.vim
if &compatible
  set nocompatible
endif

" Required:
set runtimepath+=~/.vim/bundles/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.vim/bundle')
  call dein#begin('~/.vim/bundle')

  " Let dein manage dein
  " Required:
  call dein#add('~/.vim/bundles/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  " You can specify revision/branch/tag.
  call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

  call dein#add('bronson/vim-trailing-whitespace')

  " Required:
  call dein#end()
  call dein#save_state()
endif

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf.vim'
Plug 'jremmen/vim-ripgrep'
Plug '/usr/local/opt/fzf'
call plug#end()


" Required:
filetype plugin indent on
syntax enable

if dein#check_install()
  call dein#install()
endif

nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
noremap h <NOP>
noremap l <NOP>
