set number
set tabstop=2
set expandtab
set shiftwidth=2
set nobackup
set noswapfile
set cursorline
set cursorcolumn
set hlsearch
set nowrap
set autoread
colorscheme molokai
set t_Co=256
set background=dark
syntax on

" call dein#add('bronson/vim-trailing-whitespace')

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf.vim'
Plug 'jremmen/vim-ripgrep'
Plug '~/.fzf'
call plug#end()


" Required:
filetype plugin indent on
syntax enable

nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>

" :PlugInstall
