---
-
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  tasks:
    - name: pacman -Sy
      pacman:
        update_cache: yes
        upgrade: yes

    - name: pacman -S gcc
      pacman:
        name: gcc
        state: present

    - name: pacman -S openssh
      pacman:
        name: openssh
        state: present

    - name: pacman -S git
      pacman:
        name: git
        state: present

    - name: pacman -S docker
      pacman:
        name: docker
        state: present

    - name: pacman -S docker-compose
      pacman:
        name: docker-compose
        state: present

    - name: pacman -S vim
      pacman:
        name: vim
        state: present

    - name: pacman -S tmux
      pacman:
        name: tmux
        state: present

    - name: pacman -S curl
      pacman:
        name: curl
        state: present

    - pacman:
        name: fcitx
        state: present

    - pacman:
        name: fcitx-mozc
        state: present

    - pacman:
        name: fcitx-configtool
        state: present

    - pacman:
        name: zip
        state: present

    - pacman:
        name: unzip
        state: present

    - pacman:
        name: go
        state: present

    - pacman:
        name: ruby
        state: present

    - pacman:
        name: python-pexpect
        state: present

    - pacman:
        name: noto-fonts
        state: present

    - pacman:
        name: noto-fonts-cjk
        state: present

    - pacman:
        name: noto-fonts-emoji
        state: present

    - pacman:
        name: ripgrep
        state: present

    - name: pacman -S wpa_supplicant
      pacman:
        name: wpa_supplicant
        state: present

    - name: pacman -S iw
      pacman:
        name: iw
        state: present

    - name: pacman -S ntfs-3g
      pacman:
        name: ntfs-3g
        state: present

    - name: Make sure bluetooth is running
      systemd:
        name: bluetooth
        state: started
        enabled: yes

    - name: Make sure NetworkManager is running
      systemd:
        name: NetworkManager
        state: started
        enabled: yes

-
  hosts: localhost
  connection: local
  gather_facts: false
  become: kentas
  tasks:
    - git_config:
        name: user.name
        scope: global
        state: present
        value: kenta-s

    - git_config:
        name: user.email
        scope: global
        state: present
        value: knt01222@gmail.com

    - name: apply Emacs keybind 1
      file:
        path: ~/.config/gtk-3.0/settings.ini
        state: touch
        mode: u+rw,g+rw,o+rw
        modification_time: preserve
        access_time: preserve

    - name: apply Emacs keybind 2
      lineinfile:
        path: ~/.config/gtk-3.0/settings.ini
        regexp: '^\[Settings\]$'
        line: '[Settings]'

    - name: apply Emacs keybind 3
      lineinfile:
        path: ~/.config/gtk-3.0/settings.ini
        regexp: '^gtk-key-theme-name='
        line: 'gtk-key-theme-name=Emacs'

    - name: make CapsLock into Ctrl 1
      file:
        path: ~/.Xmodmap
        state: touch
        mode: u+rw,g+rw,o+rw
        modification_time: preserve
        access_time: preserve

    - name: make CapsLock into Ctrl 2
      lineinfile:
        path: ~/.Xmodmap
        regexp: '^remove Lock = Caps_Lock$'
        line: 'remove Lock = Caps_Lock'

    - name: make CapsLock into Ctrl 3
      lineinfile:
        path: ~/.Xmodmap
        regexp: '^keysym Caps_Lock = Control_L$'
        line: 'keysym Caps_Lock = Control_L'

    - name: make CapsLock into Ctrl 4
      lineinfile:
        path: ~/.Xmodmap
        regexp: '^add Control = Control_L$'
        line: 'add Control = Control_L'

    - file:
        path: ~/.xprofile
        state: touch
        mode: u+rw,g+rw,o+rw
        modification_time: preserve
        access_time: preserve

    - lineinfile:
        path: ~/.xprofile
        regexp: '^export GTK_IM_MODULE=fcitx$'
        line: 'export GTK_IM_MODULE=fcitx'

    - lineinfile:
        path: ~/.xprofile
        regexp: '^export QT_IM_MODULE=fcitx$'
        line: 'export QT_IM_MODULE=fcitx'

    - lineinfile:
        path: ~/.xprofile
        regexp: '^export XMODIFIERS=@im=fcitx$'
        line: 'export XMODIFIERS=@im=fcitx'

    - file:
        path: ~/.config/locale.conf
        state: touch
        mode: u+rw,g+rw,o+rw
        modification_time: preserve
        access_time: preserve

    - lineinfile:
        path: ~/.config/locale.conf
        regexp: '^LC_CTYPE='
        line: 'LC_CTYPE=ja_JP.UTF-8'

    - name: git clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf

    - name: install fzf
      shell: ~/.fzf/install && touch ~/.fzf/installed
      args:
        creates: ~/.fzf/installed

    - name: install vim-plug
      command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: ~/.vim/autoload/plug.vim

    - name: git clone yay
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: ~/.yay
    
    # TODO: I could not make this work. please run this mannualy
    # - name: install yay
    #   command: makepkg -si && touch ~/.yay/installed
    #   args:
    #     chdir: ~/.yay
    #     creates: ~/.yay/installed

    # this takes a few minutes
    - name: install google-chrome
      expect:
        command: yay -S google-chrome
        responses:
         'Enter a number \(default=1\)': '1'
         '\=\=\>': 'A'
         '\=\=\>': 'N'
      args:
        creates: ~/.cache/yay/google-chrome
