---
-
  hosts: all
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: apt install gcc
      apt:
        name: gcc
        state: present

    - name: apt install git
      apt:
        name: git
        state: present

    - name: apt install docker
      apt:
        name: docker
        state: present

    - name: apt install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: apt install vim
      apt:
        name: vim
        state: present

    - name: apt install tmux
      apt:
        name: tmux
        state: present

    - name: apt install curl
      apt:
        name: curl
        state: present

    - name: make CapsLock into Ctrl
      lineinfile:
        path: /etc/default/keyboard
        regexp: '^XKBOPTIONS='
        line: 'XKBOPTIONS="ctrl:nocaps"'

    - name: systemctl restart console-setup
      systemd:
        name: console-setup
        state: restarted

    - name: git clone fzf
      become: no
      git:
        repo: git@github.com:junegunn/fzf.git
        dest: ~/.fzf

    - name: install fzf
      become: no
      shell: ~/.fzf/install && touch ~/.fzf/installed
      args:
        creates: ~/.fzf/installed

    - name: install vim-plug
      become: no
      command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: ~/.vim/autoload/plug.vim
