---
-
  hosts: all
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: apt install gcc
      apt:
        name: gcc
        state: present

    - name: apt install git
      apt:
        name: git
        state: present

    - name: apt install build-essential
      apt:
        name: build-essential
        state: present

    - name: apt install libssl-dev
      apt:
        name: libssl-dev
        state: present

    - name: apt install libreadline-dev
      apt:
        name: libreadline-dev
        state: present

    - name: apt install zlib1g-dev
      apt:
        name: zlib1g-dev
        state: present

    - name: apt install docker
      apt:
        name: docker
        state: present

    - name: apt install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: apt install vim
      apt:
        name: vim
        state: present

    - name: apt install tmux
      apt:
        name: tmux
        state: present

    - name: apt install curl
      apt:
        name: curl
        state: present

    - name: apt install xsel
      apt:
        name: xsel
        state: present

    - name: apt install exfat-fuse
      apt:
        name: exfat-fuse
        state: present

    - name: apt install exfat-utils
      apt:
        name: exfat-utils
        state: present

    - name: make CapsLock into Ctrl
      lineinfile:
        path: /etc/default/keyboard
        regexp: '^XKBOPTIONS='
        line: 'XKBOPTIONS="ctrl:nocaps"'

    - name: git clone fzf
      become: no
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf

    - name: install fzf
      become: no
      shell: ~/.fzf/install && touch ~/.fzf/installed
      args:
        creates: ~/.fzf/installed

    - name: install vim-plug
      become: no
      command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: ~/.vim/autoload/plug.vim

    - name: install rbenv
      become: no
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: ~/.rbenv

    - name: add rbenv path
      become: no
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

    - name: add rbenv init to bashrc
      become: no
      lineinfile:
        path: ~/.bashrc
        line: 'eval "$(rbenv init -)"'

    - name: Create a plugin directory in rbenv root
      become: no
      file:
        path: ~/.rbenv/plugins
        state: directory

    - name: git clone ruby-build
      become: no
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build

    - name: git clone ruby-build
      become: no
      git:
        repo: https://github.com/nodenv/nodenv.git
        dest:  ~/.nodenv

    - name: add nodenv path
      become: no
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="$HOME/.nodenv/bin:$PATH"'

    - name: add nodenv init
      become: no
      lineinfile:
        path: ~/.bashrc
        line: 'eval "$(nodenv init -)"'

    - name: mkdir nodenv/plugins
      become: no
      file: path=~/.nodenv/plugins state=directory mode=0755

    - name: git clone node-build
      become: no
      git:
        repo: https://github.com/nodenv/node-build.git
        dest:  ~/.nodenv/plugins/node-build

    - name: git pull in nodenv dir
      become: no
      shell: git pull
      args:
        chdir: ~/.nodenv
